spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/zenqara_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    producer:
      bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
      addTypeHeaders: false

    topic:
      name: post-events

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: 8081
  servlet:
    context-path: /api/v1

user-service:
  port: 8080
  host: ${USER_SERVICE_HOST:localhost}
