spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/zenqara_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: 8081
  servlet:
    context-path: /api/v1

user-service:
  port: 8080
  host: localhost
